### ISSUE TITLE
error

### ISSUE THREAD

**Issue by our-cakes** [KimJun1010/WeblogicTool#10]
============检查漏洞：CVE_2020_14882_Unauthorized开始============
[*]出现异常：ConnectException: Connection refused (Connection refused)，Cause：java.net.ConnectException: Connection refused (Connection refused)
============检查漏洞：CVE_2020_14882_Unauthorized完成============

**Comment by KimJun1010** [comment]
应该是 waf 拦截了

**Comment by our-cakes** [comment]
> 应该是 waf 拦截了

我自己的靶场环境，也试过一些在线的靶场环境

**Comment by KimJun1010** [comment]
有在线的测试地址吗？

**Comment by our-cakes** [comment]
> 有在线的测试地址吗？

稍等，我开一个

**Comment by our-cakes** [comment]
> 有在线的测试地址吗？

http://123.58.224.8:42757

**Comment by our-cakes** [comment]
> > 有在线的测试地址吗？
> 
> http://123.58.224.8:42757

14882

**Comment by KimJun1010** [comment]
我这边测试没问题呢😂
<img width="893" alt="image" src="https://github.com/KimJun1010/WeblogicTool/assets/49397311/3e6f9a67-1e2a-4994-af56-356899291342">

**Comment by our-cakes** [comment]
啊？我是mac m1环境,用的jdk1.8，不应该啊
============检查漏洞：CVE_2020_14882_Unauthorized开始============
[*]出现异常：ConnectException: Connection refused (Connection refused)，Cause：java.net.ConnectException: Connection refused (Connection refused)
============检查漏洞：CVE_2020_14882_Unauthorized完成============

**Comment by our-cakes** [comment]
我同事的win环境也有问题

**Comment by KimJun1010** [comment]
你用的哪个版本，1.3测试可以的

**Comment by our-cakes** [comment]
> 你用的哪个版本，1.3测试可以的

就是1.3

**Comment by KimJun1010** [comment]
看看是不是挂了代理问题；换个热点网络；抓包看看

**Comment by our-cakes** [comment]
> 看看是不是挂了代理问题；换个热点网络；抓包看看

发现了问题：我直接-jar 打开工具,直接去扫14882,是直接显示拒接连接的，没有发包，但我如果去扫一下2551echo，再扫14882，他就发包了，然后就扫出来了，大佬你换过其他环境来测试吗，我好几个同事pc都是和我一样的问题

**Comment by KimJun1010** [comment]
我也是命令行启动，直接扫14882，但是结果正常。。。
java version "1.8.0_181"

**Comment by our-cakes** [comment]
> 我也是命令行启动，直接扫14882，但是结果正常。。。 java version "1.8.0_181"

cake@MacBook-Air weblogic-exp % java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
我麻了

**Comment by KimJun1010** [comment]
可能是371版本问题，换个低一点的181版本试试看

**Comment by our-cakes** [comment]
> 181版

大佬啥系统

**Comment by KimJun1010** [comment]
> > 181版
> 
> 大佬啥系统

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
。。。
