### ISSUE TITLE
java

### ISSUE THREAD

**Issue by mumu0215** [KimJun1010/WeblogicTool#2]

**Comment by mumu0215** [comment]
<img width="815" alt="Snipaste_2023-05-23_17-02-04" src="https://github.com/KimJun1010/WeblogicTool/assets/40090857/3e52fd1a-18cb-4f0e-ad5d-2d836322d273">

**Comment by KimJun1010** [comment]
> <img alt="Snipaste_2023-05-23_17-02-04" width="815" src="https://user-images.githubusercontent.com/40090857/240209725-3e52fd1a-18cb-4f0e-ad5d-2d836322d273.png">

可能是网络异常，多试几次
