### ISSUE TITLE
师傅好，能请你打包个m2能用的吗哈哈哈

### ISSUE THREAD

**Issue by Layjb** [KimJun1010/WeblogicTool#3]

**Comment by KimJun1010** [comment]
用JDK8 启动就可以了，jar跨平台的，m2应该没问题的呢

**Comment by Layjb** [comment]
<img width="606" alt="image" src="https://github.com/KimJun1010/WeblogicTool/assets/56261934/09cb51ed-7c9c-4908-8a64-46a09b7471db">
实不相瞒，我很难受

**Comment by Layjb** [comment]
<img width="610" alt="image" src="https://github.com/KimJun1010/WeblogicTool/assets/56261934/fe9bc426-ff85-4573-bbdd-d655ae9b8a0f">
实不相瞒，我很难受

**Comment by KimJun1010** [comment]
> <img alt="image" width="610" src="https://user-images.githubusercontent.com/56261934/256563479-fe9bc426-ff85-4573-bbdd-d655ae9b8a0f.png"> 实不相瞒，我很难受

换低一点的版本  181的
