### ISSUE TITLE
找不到或无法加载主类 com.itkim.HelloApplication

### ISSUE THREAD

**Issue by ghost** [KimJun1010/WeblogicTool#4]
尝试了几个版本的jdk,也放置了需要的jar包. 目前还是提示这个问题. 不知是我本地环境配置有误还是什么其他的问题. 请检查一下,谢谢.目前java版本:
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
javac 1.8.0_342

**Comment by KimJun1010** [comment]
> 尝试了几个版本的jdk,也放置了需要的jar包. 目前还是提示这个问题. 不知是我本地环境配置有误还是什么其他的问题. 请检查一下,谢谢.目前java版本:
> openjdk version "1.8.0_342"
> OpenJDK Runtime Environment (build 1.8.0_342-b07)
> OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
> javac 1.8.0_342

1.8.0_342版本太高了，可以用1.8.0_181的
